#!/bin/sh
# /usr/bin/qos-bandwidth-sweep.sh — run every 5 minutes by cron (see
# 18-provision-qos-bandwidth-api.sh). For every uci firewall rule this
# project created for QoS Priority marking (named `qospriority-<mac with
# colons stripped>`, see docker/provision/www/api/qos-priority), reads that
# device's real nft mangle_forward counter (tcp+udp summed — a single
# qos-priority uci rule with no explicit `proto` expands into TWO separate
# nft rules, one per protocol, confirmed live: docker/README.md's
# qos-priority section shows the real nft output, one line per protocol;
# Section 19 below is the reset-mechanism finding, not this one) and
# accumulates the DELTA since this script's own last observation onto a
# persisted per-device-per-UTC-day running total.
#
# Why accumulate a delta, not the raw counter itself: `nft reset` does not
# work on this VM (confirmed live, docker/facts.md Section 19 — every
# documented reset form left a known non-zero counter completely
# unchanged). `fw4 reload` DOES reliably zero every counter in the table
# (as a side effect of fully regenerating the whole ruleset from uci
# config from scratch), and this script calls it once at the end of every
# tick — but fw4 reload is ALSO called by EVERY existing write endpoint in
# this project (device-pause, qos-priority itself, device-bedtime,
# firewall-rules, etc.), not just by this sweep's own purpose-built call,
# so the raw counter can be zeroed by something totally unrelated at any
# moment, not just at a controlled boundary this script owns.
#
# CRITICAL BUG FIXED (whole-feature integration code review, Wave 9): an
# earlier version of this script always computed
# NEW_TOTAL = PREV_TOTAL + BYTES_NOW (the raw counter's absolute value),
# which is only correct if the counter was truly reset to 0 since the
# last tick. That version assumed its own end-of-tick `fw4 reload` call
# always achieved that reset, but never verified it — the call's failure
# was only logged (see the ERROR log below), not otherwise handled. If
# that reload ever failed (fw4's own `nft -f` invocation can fail for
# reasons entirely unrelated to this script — e.g. a bad rule generated by
# some other write endpoint's uci state, disk pressure), the raw counter
# kept growing instead of resetting, and the next tick added that ENTIRE
# still-growing raw value on top of a total that had already counted the
# earlier portion — a genuine double-count/overcount, directly
# contradicting the "undercounts, never overcounts" guarantee this script
# and its docs made. This is a documented, reasoned fix for that finding,
# not a hedge.
#
# THE FIX: this script now tracks, per device, the raw counter value IT
# last observed (${STATE_DIR}/<mac-no-colons>.lastraw.txt — NOT date-keyed;
# unlike the accumulated total, this tracks the hardware counter's own
# continuous state, which has no concept of calendar days). Each tick:
#   - if BYTES_NOW >= LAST_RAW: nothing has reset the counter since we
#     last looked (whether or not this script's own prior reload
#     succeeded is irrelevant here — the counter clearly hasn't dropped
#     below what we last saw), so DELTA = BYTES_NOW - LAST_RAW.
#   - if BYTES_NOW < LAST_RAW: the counter is lower than what we last
#     observed, so SOMETHING (this script's own reload, or some other
#     write endpoint's) reset it since then, and it has been growing from
#     0 ever since — so the whole current BYTES_NOW value IS the delta:
#     DELTA = BYTES_NOW.
# DELTA (never the raw BYTES_NOW itself) is what gets added onto
# PREV_TOTAL. lastraw.txt is updated to BYTES_NOW unconditionally, every
# tick, regardless of whether this tick's own end-of-loop `fw4 reload`
# call (still made once below, exactly as before) succeeds or fails —
# that call is no longer load-bearing for correctness, only for keeping
# the raw counter bounded/small over time.
#
# This makes the accumulation correct REGARDLESS of whether fw4 reload
# succeeds: a successful reload drops the raw counter, so next tick's
# BYTES_NOW < LAST_RAW branch correctly detects the reset (no data lost —
# this preserves the pre-existing, already-correct undercount-only
# behavior below, unchanged). A failed reload leaves the raw counter
# growing, so next tick's BYTES_NOW >= LAST_RAW branch correctly counts
# only the new traffic since it was last observed (no double-count). The
# one remaining disclosed limitation is a genuine undercount, not an
# overcount: if an UNRELATED fw4 reload (from some other write endpoint)
# happens BETWEEN two sweep ticks, whatever traffic accumulated in that
# gap is lost (the counter is already back to zero, and LAST_RAW already
# reflects the pre-reset value, by the time this sweep next reads it) —
# an undercount, never an overcount, for that one device that day. Rare
# in practice (write actions aren't constant), and documented plainly
# rather than glossed over — see docker/README.md's Known Limitations
# and docs/superpowers/specs/2026-09-02-qos-bandwidth-today-design.md. A
# separate, purely theoretical, bounded-growth concern (NOT a correctness
# concern): if fw4 reload failed on every single tick indefinitely, a
# device's raw nft counter would keep growing without ever being zeroed —
# still summed correctly via the delta above, but worth noting as a
# storage/counter-size consideration over a very long unbroken failure
# streak, not a reason totals would ever be wrong.
#
# Storage: /etc/qos-bandwidth/<mac-no-colons>-<YYYYMMDD>.txt, one plain
# integer (accumulated bytes) per device per UTC calendar day, plus
# /etc/qos-bandwidth/<mac-no-colons>.lastraw.txt, one plain integer (this
# script's last-observed raw counter value) per device, NOT date-keyed. A
# new day is simply a filename that doesn't exist yet (read as 0) — no
# hour-comparison arithmetic anywhere in this script, deliberately
# avoiding the busybox-ash `$(( ))` zero-padded-hour gotcha bedtime-
# sweep.sh had to route around (docker/facts.md Section 16) by not needing
# hour arithmetic at all. Byte totals ARE run through `$(( ))` below, so
# all operands (PREV_TOTAL, BYTES_NOW, and now LAST_RAW too) are
# defensively stripped of any leading zeros first — this project's own
# arithmetic values should never naturally have one (shell arithmetic
# never prints a zero-padded result), but a corrupted/manually-edited
# state file could, and a leading-zero digit sequence in $(( )) risks the
# exact same octal-misinterpretation bug class bedtime-sweep.sh found, so
# this is defensive, not decorative.
#
# No top-level `set -e`, deliberately, same reasoning as devpause-sweep.sh
# and bedtime-sweep.sh: one device's read/write failing shouldn't cancel
# the sweep for every other device this tick.

STATE_DIR="/etc/qos-bandwidth"
if ! mkdir -p "$STATE_DIR"; then
  logger -t qos-bandwidth-sweep "ERROR: mkdir -p ${STATE_DIR} failed; every write this tick will fail"
fi

TODAY="$(date -u +%Y%m%d)"

# `local` inside a function is a busybox ash extension, not POSIX-standard —
# confirmed working on this VM's actual ash (code review, live-sourced and
# exercised: "007"->"7", "0"->"0", ""->"0", all EXIT=0), not assumed to work
# just because it's common. Same scrutiny this project already applied to
# the `10#$HOUR` ash portability assumption that did NOT hold (Section 16).
strip_leading_zeros() {
  # "007" -> "7", "0" -> "0", "" -> "0". Avoids $(( )) octal
  # misinterpretation on a leading-zero digit string.
  local v
  v="$(echo "$1" | sed 's/^0*//')"
  if [ -z "$v" ]; then echo 0; else echo "$v"; fi
}

for id in $(uci show firewall | grep "\.name='qospriority-" | sed -n "s/^firewall\.\([^.]*\)\.name=.*/\1/p"); do
  MAC="$(uci -q get "firewall.${id}.src_mac")"
  if [ -z "$MAC" ]; then
    logger -t qos-bandwidth-sweep "ERROR: firewall.${id} has no src_mac; skipping"
    continue
  fi
  MAC_NOCOLON="$(echo "$MAC" | tr -d ':' | tr 'A-F' 'a-f')"
  RULE_NAME="qospriority-${MAC_NOCOLON}"

  NFT_OUTPUT="$(nft list chain inet fw4 mangle_forward 2>/dev/null)"
  NFT_STATUS=$?
  if [ "$NFT_STATUS" != "0" ]; then
    logger -t qos-bandwidth-sweep "ERROR: nft list chain inet fw4 mangle_forward failed (exit ${NFT_STATUS}); skipping ${RULE_NAME} this tick"
    continue
  fi

  # Sum both nft rule lines' bytes for this device's mark rule (tcp + udp —
  # a single uci rule with no explicit proto expands into both, confirmed
  # live in docker/README.md's qos-priority section). Each matching line
  # looks like:
  #   ... counter packets N bytes M ... comment "!fw4: qospriority-aabbccddeeff"
  BYTES_NOW="$(echo "$NFT_OUTPUT" \
    | grep "\"!fw4: ${RULE_NAME}\"" \
    | sed -n 's/.*counter packets [0-9]* bytes \([0-9]*\).*/\1/p' \
    | awk '{sum+=$1} END {print sum+0}')"
  BYTES_NOW="$(strip_leading_zeros "$BYTES_NOW")"

  # Delta-tracking against the last raw counter value THIS script itself
  # observed for this device (not date-keyed — the hardware counter has no
  # concept of calendar days). See the header comment above for the full
  # reasoning: this is what makes the accumulation correct whether or not
  # this tick's (or any prior tick's) `fw4 reload` call actually succeeded.
  LASTRAW_FILE="${STATE_DIR}/${MAC_NOCOLON}.lastraw.txt"
  LAST_RAW="$(cat "$LASTRAW_FILE" 2>/dev/null)"
  case "$LAST_RAW" in
    ''|*[!0-9]*) LAST_RAW=0 ;;
  esac
  LAST_RAW="$(strip_leading_zeros "$LAST_RAW")"

  if [ "$BYTES_NOW" -ge "$LAST_RAW" ]; then
    # Normal case: counter has been growing (or unchanged) since we last
    # looked — count only the new traffic since then, regardless of
    # whether a reset happened to occur (it clearly hasn't, or BYTES_NOW
    # would be lower than LAST_RAW).
    DELTA=$((BYTES_NOW - LAST_RAW))
  else
    # Counter is lower than what we last observed: something (this
    # script's own reload, or some other write endpoint's) reset it since
    # then, and it has been growing from 0 ever since — the whole current
    # value IS the delta. Do NOT subtract LAST_RAW here; that would
    # produce a negative/nonsensical value.
    DELTA=$BYTES_NOW
  fi

  STATE_FILE="${STATE_DIR}/${MAC_NOCOLON}-${TODAY}.txt"
  PREV_TOTAL="$(cat "$STATE_FILE" 2>/dev/null)"
  case "$PREV_TOTAL" in
    ''|*[!0-9]*) PREV_TOTAL=0 ;;
  esac
  PREV_TOTAL="$(strip_leading_zeros "$PREV_TOTAL")"

  NEW_TOTAL=$((PREV_TOTAL + DELTA))
  echo "$NEW_TOTAL" > "$STATE_FILE" \
    || logger -t qos-bandwidth-sweep "ERROR: failed to write ${STATE_FILE}"

  # Updated unconditionally, regardless of whether this tick's later fw4
  # reload call (below) succeeds or fails — that's exactly what makes the
  # accumulation above correct independent of the reload's outcome.
  echo "$BYTES_NOW" > "$LASTRAW_FILE" \
    || logger -t qos-bandwidth-sweep "ERROR: failed to write ${LASTRAW_FILE}"
done

# Zero every counter in the table for the next window — the only working
# reset mechanism on this VM (docker/facts.md Section 19). Safe to call
# even when the for-loop above ran zero times (no qos-priority devices
# marked yet) — fw4 reload is idempotent and every other sweep/endpoint in
# this project already calls it routinely. No longer load-bearing for
# correctness (see the delta-tracking fix above) — a failed reload here
# just means the raw counters stay larger until a future reload (this
# script's own or another endpoint's) eventually zeroes them; it can no
# longer cause a double-count.
if ! fw4 reload >/dev/null 2>&1; then
  logger -t qos-bandwidth-sweep "ERROR: fw4 reload failed after accumulating this tick's counters"
fi
